#ifndef _COMMANDS_H
#define _COMMANDS_H

// commands to send to target
enum
{
	// request cmds
	DEBUGGER_CMD_NONE = 0,
	DEBUGGER_CMD_CONNECT = 1,
	DEBUGGER_CMD_DISCONNECT = 2,
	DEBUGGER_CMD_STEP = 3,
	DEBUGGER_CMD_RUN = 4,
	DEBUGGER_CMD_STOP = 5,
	DEBUGGER_CMD_REQUEST_MEMORY = 6,
	DEBUGGER_CMD_REQUEST_REGISTERS = 7,

	// response types
	DEBUGGER_TARGET_RESPONSE_NONE = 128,
	DEBUGGER_TARGET_RESPONSE_CONNECTED = 129,
	DEBUGGER_TARGET_RESPONSE_DISCONNECTED = 130,
	DEBUGGER_TARGET_RESPONSE_MEMORY = 131,
	DEBUGGER_TARGET_RESPONSE_REGISTERS = 132,
	DEBUGGER_TARGET_RESPONSE_STEP = 133,
	DEBUGGER_TARGET_RESPONSE_RUN = 134,
	DEBUGGER_TARGET_RESPONSE_STOP = 135,

} _DEBUGGER_CMD_TYPE;

#endif // _COMMANDS_H